### ISSUE TITLE
Klassennamen von BarChart und PieChart ändern

### ISSUE THREAD

**Issue by ericTheShoe** [WI13C/Jgui-creator#12]
Die Klassennamen BarChart und PieChart werden gleichzeitig als Annotationen und als GUI-Komponenten verwendet.
@bimbayer

**Comment by bimbayer** [comment]
Alles klar. Wird gefixt. @LeonardMF & @VincentFederle kümmert ihr euch da drum?

**Comment by LeonardMF** [comment]
ja, wir denken uns was aus...
