### ISSUE TITLE
MockParser returns incomplete Data

### ISSUE THREAD

**Issue by ericTheShoe** [WI13C/Jgui-creator#13]
MockParser only returns the UiElemets of Type TextfieldData, BarChartData and PieChartData. While the returned datastructure can be used to create GUIs, it can't be used to alter the actual domain objects (e.g. Person, Adresse, Kontakt) yet. The MockParser is therefore subject to change.

**Comment by freeerunner** [comment]
thx, fixed mockup-parser: vorname got overwritten by nachname
