### ISSUE TITLE
Datenstruktur um Namen ergänzen

### ISSUE THREAD

**Issue by freeerunner** [WI13C/Jgui-creator#14]
@ericTheShoe Datenstruktur muss noch um Namen ergänzt werden, TextfieldData hat das z.B. schon.

**Comment by ericTheShoe** [comment]
Das Attribut 'name' wurde in die Superklasse UiElementData verschoben. Das Attribut wird jetzt vom DomainObjectParser gesetzt. Durch die zusätzliche Methode createView() in GuiGenerator kann dieser Parser einfach getestet werden:
`creator.createView(aPerson, savedListener, new DomainObjectParser());`
Vgl. [https://github.com/WI13C/Jgui-creator/commit/cbc319b07b115423c1797a5fe7ab5c2ecf29f0a1](url)
