### ISSUE TITLE
GUIKomponente Pie-Chart 

### ISSUE THREAD

**Issue by LeonardMF** [WI13C/Jgui-creator#8]
<img width="432" alt="bildschirmfoto 2016-07-20 um 14 47 08" src="https://cloud.githubusercontent.com/assets/20340014/16986801/db25eef6-4e88-11e6-8c67-602ba2f66d76.png">

**Comment by LeonardMF** [comment]
Animation
<img width="925" alt="bildschirmfoto 2016-07-20 um 14 57 38" src="https://cloud.githubusercontent.com/assets/20340014/16987057/70102d6e-4e8a-11e6-9d45-5cfb0469c665.png">

**Comment by LeonardMF** [comment]
<img width="615" alt="bildschirmfoto 2016-07-20 um 16 59 47" src="https://cloud.githubusercontent.com/assets/20340014/16991317/676e0d3c-4e9b-11e6-9dab-a6673b4a97ab.png">

**Comment by LeonardMF** [comment]
Abstimmung mit Design nötig.

**Comment by bimbayer** [comment]
Kann des sein das euer Push nicht funktioniert hat? Die Klasse PieChart besteht aus 19 LoC. Noch kein Code implementiert.

```
package de.dhbw.wi13c.jguicreator.elemente;

import java.awt.Graphics;

public class PieChart extends Chart
{
	
	public PieChart(String description){
		super(description);
	}

	@Override
	public void drawStep(Graphics g)
	{
		// TODO Auto-generated method stub
		
	}
}
```

**Comment by LeonardMF** [comment]
haben noch nicht angefangen. War ein ToDo...

**Comment by LeonardMF** [comment]
ToDo: Animation von 90° starten und im Uhrzeigersinn

**Comment by LeonardMF** [comment]
ToDo: Anzeige des Wert; Verschiedene Farben (Abstimmung auf Design)

**Comment by jenscooper** [comment]
Qualifizierter Beitrag von Jens:

Bestimmung der Koordinaten-Punkte auf einem Kreis.
https://upload.wikimedia.org/wikipedia/commons/8/82/Sinus_en_cosinus.png

**Comment by LeonardMF** [comment]
Besten Dank
