### ISSUE TITLE
GUIKomponente Bar-Chart

### ISSUE THREAD

**Issue by LeonardMF** [WI13C/Jgui-creator#9]
<img width="449" alt="bildschirmfoto 2016-07-20 um 14 49 27" src="https://cloud.githubusercontent.com/assets/20340014/16986853/28d6e182-4e89-11e6-8b24-b0e5b7a27071.png">

**Comment by LeonardMF** [comment]
Animationen
<img width="925" alt="bildschirmfoto 2016-07-20 um 14 57 38" src="https://cloud.githubusercontent.com/assets/20340014/16987044/5ab33e66-4e8a-11e6-8f5e-513154c3329b.png">

**Comment by LeonardMF** [comment]
<img width="660" alt="bildschirmfoto 2016-07-20 um 16 59 57" src="https://cloud.githubusercontent.com/assets/20340014/16991345/7ed388bc-4e9b-11e6-8b2b-aee479cecb3b.png">

**Comment by LeonardMF** [comment]
Abstimmung mit Design nötig.

**Comment by LeonardMF** [comment]
Zur Abstimmung:
(2. Vorschlag) 
<img width="669" alt="bildschirmfoto 2016-07-20 um 17 07 50" src="https://cloud.githubusercontent.com/assets/20340014/16991652/8ee2500c-4e9c-11e6-95fb-feaac6c464d6.png">

**Comment by LeonardMF** [comment]
ToDo: Methode setpanelsize() nutzen

**Comment by LeonardMF** [comment]
ToDo: initFont(schriftgröße) --> l.setfont()

**Comment by LeonardMF** [comment]
ToDo: Mouse Listener implementieren

**Comment by bimbayer** [comment]
ändert das Chart so, das es automatisch animiert und man es nicht von Hand animieren muss.

**Comment by LeonardMF** [comment]
@bimbayer: wann sollen es den animiert werden?
